use_frameworks!

platform :ios, '9.0'

target 'pLibrary_Example' do
  pod 'pLibrary', :path => '../'

  target 'pLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
